# Generated by Django 5.2.15 on 2026-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready Stock'), ('booked', 'Booked (Uang Muka)'), ('sold', 'Sold Out (Terjual)')], default='ready', max_length=10, verbose_name='Status Stok'),
        ),
    ]
